name: Ericvanhorrik
favicon: null
layout_spectrum: 0.866798380156979
typography_spectrum: 0.8728146876674145
title: Making memories
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9660449635703117
  lightness: 0.5814535722602159
  saturation: 0.13108151126652956
  rhythmicContrast: 0.2590318536385894
purpose: []
