name: Eric van Horrik Fotografie
favicon: null
layout_spectrum: 0.24508
typography_spectrum: 0.07373
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#14292e'
    - '#e5dfe1'
    - '#bebab9'
    - '#475256'
    - '#979694'
  brandStrength: 0.5
  lightness: 0.5814535722602159
  saturation: 0.13108151126652956
  rhythmicContrast: 0.2590318536385894
purpose: []
